# Setup
title:        بوت استرپ فارسی
tagline:      نسخه فارسی و راستچین بوت استرپ با فونت وزیر
baseurl:      ""
paginate:     1
locale:       "fa"

# About/contact
author:
  name:       امید شهسوارزاده
  url:        http://omidsh.ir 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown